version: '2'
services:
  rf_skeleton_app:
    restart: always
    container_name: rf_skeleton_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www